### ISSUE TITLE
Add test.pypi.org support to the build pipeline

### ISSUE THREAD

**Issue by oliverandrich** [django-commons/django-tailwind-cli#134]

**Comment by oliverandrich** [comment]
@cunla @Stormheg during the transition of the project, we were not able to add support for test.pypi.org. Finally, I have my account up and running again. Shall I still do it, or with the soon to happen transition of the PyPI project towards you guys, shall we wait and you setup the test.pypi.org project? Any advice on this?

**Comment by cunla** [comment]
Hi @oliverandrich, thanks for following up on that! please add Storm and me as owners in test.pypi.org. 

In the admin team we have decided not to remove package maintainers on pypi for now (in case you need to yank a version or something of that sort), so there pending actions to do on pypi.org (prod). @tim-schilling we should document this decision somewhere.

Are you good with setting up the workflow to publish to test.pypi.org? Let me know if you need help with that.

**Comment by Stormheg** [comment]
@oliverandrich if you have never uploaded this package to Test PyPI before and are comfortable setting this up yourself, you should create a 'pending' trusted publisher: https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/

Use `release.yml` for the workflow name, and `testpypi` as environment name.

Next, uncomment the commented bits: https://github.com/django-commons/django-tailwind-cli/blob/c9b3895ed083dccd0100062b77705e2da25f6c4b/.github/workflows/release.yml#L97-L121

**Comment by oliverandrich** [comment]
@cunla @Stormheg I have added you to the corresponding testpypi project as owners. I hope I have done everything correctly. The addition of the workflow in release.yml has also been done. The 2.20.2 release worked as expected. Closing this issue.

**Comment by Stormheg** [comment]
Received the invite and accepted. Thank you Oliver! 👍 👍
