### ISSUE TITLE
Repo documentation links

### ISSUE THREAD

**Issue by katterfelto** [django-commons/django-tailwind-cli#136]
Hi I’m just investigating tailwindcss form my django project, this looks like it might work form me but I had issues with your documentation.

All the links point to [rtfs.io.me](https://django-tailwind-cli.rtfd.io.me/) but the pages seem to be hosted on [readthedocs.io](https://django-tailwind-cli.readthedocs.io/)

**Comment by oliverandrich** [comment]
Fixed. I updated the broken links and link definitions. Thanks for reporting.
